const CPU = @import("CPU.zig").CPU;

const LIST = [_] *const fn (*CPU) void 
{
    &CPU.SPECIAL,  &CPU.BcondZ,
    &CPU.J,        &CPU.JAL,
    &CPU.BEQ,      &CPU.BNE,
    &CPU.BLEZ,     &CPU.BGTZ,
    &CPU.ADDI,     &CPU.ADDIU,
    &CPU.SLTI,     &CPU.SLTIU,
    &CPU.ANDI,     &CPU.ORI,
    &CPU.XORI,     &CPU.LUI,
    &CPU.COP0,     &CPU.COP1,
    &CPU.COP2,     &CPU.COP3,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.LB,       &CPU.LH,
    &CPU.LWL,      &CPU.LW,
    &CPU.LBU,      &CPU.LHU,
    &CPU.LWR,      &CPU.XXX,
    &CPU.SB,       &CPU.SH,
    &CPU.SWL,      &CPU.SW,
    &CPU.XXX,      &CPU.XXX,
    &CPU.SWR,      &CPU.XXX,
    &CPU.LWC0,     &CPU.LWC1,
    &CPU.LWC2,     &CPU.LWC3,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.SWC0,     &CPU.SWC1,
    &CPU.SWC2,     &CPU.SWC3,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
};
const SUB_LIST = [_] *const fn (*CPU) void 
{
    &CPU.SLL,      &CPU.XXX,
    &CPU.SRL,      &CPU.SRA,
    &CPU.SLLV,     &CPU.XXX,
    &CPU.SRLV,     &CPU.SRAV,
    &CPU.JR,       &CPU.JALR,
    &CPU.XXX,      &CPU.XXX,
    &CPU.SYSCALL,  &CPU.BREAK,
    &CPU.XXX,      &CPU.XXX,
    &CPU.MFHI,     &CPU.MTHI,
    &CPU.MFLO,     &CPU.MTLO,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.MULT,     &CPU.MULTU,
    &CPU.DIV,      &CPU.DIVU,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.ADD,      &CPU.ADDU,
    &CPU.SUB,      &CPU.SUBU,
    &CPU.AND,      &CPU.OR,
    &CPU.XOR,      &CPU.NOR,
    &CPU.XXX,      &CPU.XXX,
    &CPU.SLT,      &CPU.SLTU,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
    &CPU.XXX,      &CPU.XXX,
};